# Generated by Django 3.2.21 on 2023-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='age',
            field=models.IntegerField(verbose_name='姓名'),
        ),
    ]
