# Generated by Django 3.2.21 on 2023-09-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_employee_table_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已出售'), (2, '未出售')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department', verbose_name='部门'),
        ),
    ]
