# Generated by Django 3.2.21 on 2023-10-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='价格')),
                ('sale_situation', models.SmallIntegerField(choices=[(1, '未出售'), (2, '已出售')], default=1, verbose_name='出售情况')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='下单用户')),
            ],
        ),
    ]
